### ISSUE TITLE
Potential contributions for consideration

### ISSUE THREAD

**Issue by hunhoffe** [makslevental/mlir-python-extras#102]
I have made a few modifications to `mlir-python-extras` code, and I am unsure if they are suitable for upstreaming. I wanted to get your opinions on them before I take the time to submit a PR. I appreciate your consideration!

# 1. `_for` with automatic yield insertion

I wanted to be able to write something like below (notice no scf `yield_` statement at the end of the loop body):
```python
from my.extras import _for as range_

...
for i in range_(10):
    # do work
    ...
```
To do this, I created my own specialization of the `_for` wrapper, with a new parameter that can toggle whether a yield (with no result) is automatically inserted or not. Code for that is here: https://github.com/Xilinx/mlir-aie/blob/9c52fe0a18004f7280f0787679560150f12971f1/python/extras/dialects/ext/scf.py#L10

# 2. Specialization of the function/`call` argument/return handling

This one I really am not sure is of interest for `mlir-python-extras`, but I am making it so the user can specify `np.ndarray` types instead of `memref` types in function calls. To make this work, I had to modify a few things to do with `call` and `function`. I haven't teased apart exactly what might be upstreamable or not, but let me know if there's any interest in integration. Code is here: https://github.com/Xilinx/mlir-aie/blob/08b13e6325e45e2d3df1e8dbbcf1f3e3e0532c2c/python/helpers/dialects/ext/func.py#L1

**Comment by makslevental** [comment]
> I have made a few modifications to mlir-python-extras code, and I am unsure if they are suitable for upstreaming

upstreaming here or llvm/mlir?

> I wanted to be able to write something like below (notice no scf yield_ statement at the end of the loop body):

In this project/repo/thing [this is already possible](https://github.com/makslevental/mlir-python-extras/blob/main/tests/test_scf.py#L466-L473) (in addition to various other things):

```python
    def iffoo():
        one = constant(1.0)
        two = constant(2.0)
        if one < two:
            three = constant(3.0)
            for i in range_(0, 10):
                four = constant(4.0)
                five = constant(5.0)
        else:
            for i in range_(0, 10):
                four = constant(6.0)
                five = constant(7.0)
```

but using a mechanism that I felt was too spicy for mlir-aie ([ast rewriting](https://github.com/makslevental/mlir-python-extras/blob/main/mlir/extras/dialects/ext/scf.py#L439-L448)). 

> This one I really am not sure is of interest for mlir-python-extras, but I am making it so the user can specify np.ndarray types instead of memref types in function calls.

yea this one is "beyond scope" - this repo/project/thing is purely about wrapping/binding/emitting mlir. The various connections to numpy are incidental (primarily for testing runtime connections).

**Comment by hunhoffe** [comment]
1. I was just thinking about upstreaming here.

2. Yes, I think maybe ast rewriting isn't exactly the right fit for mlir-aie at this time, but it's good to know it's an option for the future. Since you already have a mechanism here, I will assume you are not interested in a second mechanism.

3. Yes, that delineation makes sense to me!

Thanks for your time and responses! I'll close this now, as I believe I have my answer that my local changes should remain local.
